# permissions for end users to edit composabilityrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: composabilityrequest-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cro
    app.kubernetes.io/part-of: cro
    app.kubernetes.io/managed-by: kustomize
  name: composabilityrequest-editor-role
rules:
- apiGroups:
  - cro.hpsys.ibm.ie.com
  resources:
  - composabilityrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cro.hpsys.ibm.ie.com
  resources:
  - composabilityrequests/status
  verbs:
  - get
