# permissions for end users to view composabilityrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: composabilityrequest-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cro
    app.kubernetes.io/part-of: cro
    app.kubernetes.io/managed-by: kustomize
  name: composabilityrequest-viewer-role
rules:
- apiGroups:
  - cro.hpsys.ibm.ie.com
  resources:
  - composabilityrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cro.hpsys.ibm.ie.com
  resources:
  - composabilityrequests/status
  verbs:
  - get
