name: CI

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    name: Run Go Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'

      - name: Download dependencies
        run: go mod download

      - name: Fmt
        run: make fmt

      - name: Vet
        run: make vet

      - name: Build
        run: make build

      - name: Run tests
        run: make test
