name: Generate SBOM
on:
  workflow_dispatch:
  release:
    types: [published]
permissions:
  contents: read
jobs:
  generate_sbom_action:
    runs-on: ubuntu-latest
    name: Install bom and generate SBOM
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install bom
        uses: kubernetes-sigs/release-actions/setup-bom@b5b8280a60e6e20607f77068011269b982c60971 # v0.4.5
      - name: Generate SBOM
        run: |
          bom generate \
            -o composable-resource-operator_${{github.ref_name}}_sbom.spdx \
            --dirs=. \
            --namespace=https://github.com/${{ github.repository }} \
            --name=composable-resource-operator \
            --version=${{ github.ref_name }}
      - name: Generate checksum
        run: |
          sha256sum composable-resource-operator_${{github.ref_name}}_sbom.spdx > \
            composable-resource-operator_${{github.ref_name}}_sbom.spdx.sha256
      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v7
        with:
          name: sbom-${{ github.ref_name }}
          path: |
            composable-resource-operator_${{github.ref_name}}_sbom.spdx
            composable-resource-operator_${{github.ref_name}}_sbom.spdx.sha256
          retention-days: 90
      - name: Upload SBOM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{github.ref_name}}" \
            composable-resource-operator_${{github.ref_name}}_sbom.spdx \
            composable-resource-operator_${{github.ref_name}}_sbom.spdx.sha256 \
            --clobber
